# Generated by Django 3.1.3 on 2024-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symptoms', models.TextField()),
                ('cure', models.TextField()),
                ('causes', models.TextField()),
                ('prevention', models.TextField()),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('Fertilizer_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('usage_instructions', models.TextField()),
                ('composition', models.TextField()),
                ('Fertilizer_image', models.ImageField(upload_to='disease_images/')),
            ],
        ),
    ]
